package com.uhamka.app.model;
// Generated Sep 15, 2019 7:31:18 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name = "admin", catalog = "sistem_informasi")
public class Admin implements java.io.Serializable {

	private int idAdmin;
	private String username;
	private String password;
	private String email;
	private int level;

	public Admin() {
	}

	public Admin(int idAdmin, String username, String password, String email, int level) {
		this.idAdmin = idAdmin;
		this.username = username;
		this.password = password;
		this.email = email;
		this.level = level;
	}

	@Id

	@Column(name = "id_admin", unique = true, nullable = false)
	public int getIdAdmin() {
		return this.idAdmin;
	}

	public void setIdAdmin(int idAdmin) {
		this.idAdmin = idAdmin;
	}

	@Column(name = "username", nullable = false, length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "email", nullable = false, length = 150)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "level", nullable = false)
	public int getLevel() {
		return this.level;
	}

	public void setLevel(int level) {
		this.level = level;
	}

}
