package com.uhamka.app.model;
// Generated Sep 15, 2019 7:31:18 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Dosen generated by hbm2java
 */
@Entity
@Table(name = "dosen", catalog = "sistem_informasi")
public class Dosen implements java.io.Serializable {

	private String nidn;
	private String nama;
	private String alamat;
	private String nohp;
	private Set<BimbinganSkripsi> bimbinganSkripsis = new HashSet<BimbinganSkripsi>(0);

	public Dosen() {
	}

	public Dosen(String nidn, String nama, String alamat, String nohp) {
		this.nidn = nidn;
		this.nama = nama;
		this.alamat = alamat;
		this.nohp = nohp;
	}

	public Dosen(String nidn, String nama, String alamat, String nohp, Set<BimbinganSkripsi> bimbinganSkripsis) {
		this.nidn = nidn;
		this.nama = nama;
		this.alamat = alamat;
		this.nohp = nohp;
		this.bimbinganSkripsis = bimbinganSkripsis;
	}

	@Id

	@Column(name = "NIDN", unique = true, nullable = false, length = 18)
	public String getNidn() {
		return this.nidn;
	}

	public void setNidn(String nidn) {
		this.nidn = nidn;
	}

	@Column(name = "NAMA", nullable = false, length = 20)
	public String getNama() {
		return this.nama;
	}

	public void setNama(String nama) {
		this.nama = nama;
	}

	@Column(name = "ALAMAT", nullable = false, length = 50)
	public String getAlamat() {
		return this.alamat;
	}

	public void setAlamat(String alamat) {
		this.alamat = alamat;
	}

	@Column(name = "NOHP", nullable = false, length = 16)
	public String getNohp() {
		return this.nohp;
	}

	public void setNohp(String nohp) {
		this.nohp = nohp;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dosen")
	public Set<BimbinganSkripsi> getBimbinganSkripsis() {
		return this.bimbinganSkripsis;
	}

	public void setBimbinganSkripsis(Set<BimbinganSkripsi> bimbinganSkripsis) {
		this.bimbinganSkripsis = bimbinganSkripsis;
	}

}
