package com.uhamka.app.model;
// Generated Sep 15, 2019 7:31:18 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * KegiatanMahasiswa generated by hbm2java
 */
@Entity
@Table(name = "kegiatan_mahasiswa", catalog = "sistem_informasi")
public class KegiatanMahasiswa implements java.io.Serializable {

	private Integer idKgtn;
	private String jenisKegiatan;
	private String deskripsi;
	private String tipeEvent;

	public KegiatanMahasiswa() {
	}

	public KegiatanMahasiswa(String jenisKegiatan, String deskripsi, String tipeEvent) {
		this.jenisKegiatan = jenisKegiatan;
		this.deskripsi = deskripsi;
		this.tipeEvent = tipeEvent;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_kgtn", unique = true, nullable = false)
	public Integer getIdKgtn() {
		return this.idKgtn;
	}

	public void setIdKgtn(Integer idKgtn) {
		this.idKgtn = idKgtn;
	}

	@Column(name = "jenis_kegiatan", nullable = false, length = 20)
	public String getJenisKegiatan() {
		return this.jenisKegiatan;
	}

	public void setJenisKegiatan(String jenisKegiatan) {
		this.jenisKegiatan = jenisKegiatan;
	}

	@Column(name = "Deskripsi", nullable = false, length = 50)
	public String getDeskripsi() {
		return this.deskripsi;
	}

	public void setDeskripsi(String deskripsi) {
		this.deskripsi = deskripsi;
	}

	@Column(name = "Tipe_event", nullable = false, length = 16)
	public String getTipeEvent() {
		return this.tipeEvent;
	}

	public void setTipeEvent(String tipeEvent) {
		this.tipeEvent = tipeEvent;
	}

}
