package com.uhamka.app.model;
// Generated Sep 15, 2019 7:31:18 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Mahasiswa generated by hbm2java
 */
@Entity
@Table(name = "mahasiswa", catalog = "sistem_informasi")
public class Mahasiswa implements java.io.Serializable {

	private Integer nim;
	private String nama;
	private String tempatTanggalLahir;
	private String alamat;
	private String angkatan;
	private BimbinganSkripsi bimbinganSkripsi;
	private Set<Nilai> nilais = new HashSet<Nilai>(0);

	public Mahasiswa() {
	}

	public Mahasiswa(String nama, String tempatTanggalLahir, String alamat, String angkatan) {
		this.nama = nama;
		this.tempatTanggalLahir = tempatTanggalLahir;
		this.alamat = alamat;
		this.angkatan = angkatan;
	}

	public Mahasiswa(String nama, String tempatTanggalLahir, String alamat, String angkatan,
			BimbinganSkripsi bimbinganSkripsi, Set<Nilai> nilais) {
		this.nama = nama;
		this.tempatTanggalLahir = tempatTanggalLahir;
		this.alamat = alamat;
		this.angkatan = angkatan;
		this.bimbinganSkripsi = bimbinganSkripsi;
		this.nilais = nilais;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Nim", unique = true, nullable = false)
	public Integer getNim() {
		return this.nim;
	}

	public void setNim(Integer nim) {
		this.nim = nim;
	}

	@Column(name = "Nama", nullable = false, length = 30)
	public String getNama() {
		return this.nama;
	}

	public void setNama(String nama) {
		this.nama = nama;
	}

	@Column(name = "Tempat_Tanggal_Lahir", nullable = false, length = 20)
	public String getTempatTanggalLahir() {
		return this.tempatTanggalLahir;
	}

	public void setTempatTanggalLahir(String tempatTanggalLahir) {
		this.tempatTanggalLahir = tempatTanggalLahir;
	}

	@Column(name = "Alamat", nullable = false, length = 50)
	public String getAlamat() {
		return this.alamat;
	}

	public void setAlamat(String alamat) {
		this.alamat = alamat;
	}

	@Column(name = "Angkatan", nullable = false, length = 5)
	public String getAngkatan() {
		return this.angkatan;
	}

	public void setAngkatan(String angkatan) {
		this.angkatan = angkatan;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "mahasiswa")
	public BimbinganSkripsi getBimbinganSkripsi() {
		return this.bimbinganSkripsi;
	}

	public void setBimbinganSkripsi(BimbinganSkripsi bimbinganSkripsi) {
		this.bimbinganSkripsi = bimbinganSkripsi;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mahasiswa")
	public Set<Nilai> getNilais() {
		return this.nilais;
	}

	public void setNilais(Set<Nilai> nilais) {
		this.nilais = nilais;
	}

}
