package com.uhamka.app.model;
// Generated Sep 15, 2019 7:31:18 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MataKuliah generated by hbm2java
 */
@Entity
@Table(name = "mata_kuliah", catalog = "sistem_informasi")
public class MataKuliah implements java.io.Serializable {

	private Integer idMatkul;
	private String jamNgajar;
	private String namaDosen;
	private String mataKuliah;
	private String ruanganNgajar;
	private String hari;

	public MataKuliah() {
	}

	public MataKuliah(String jamNgajar, String namaDosen, String mataKuliah, String ruanganNgajar, String hari) {
		this.jamNgajar = jamNgajar;
		this.namaDosen = namaDosen;
		this.mataKuliah = mataKuliah;
		this.ruanganNgajar = ruanganNgajar;
		this.hari = hari;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_MATKUL", unique = true, nullable = false)
	public Integer getIdMatkul() {
		return this.idMatkul;
	}

	public void setIdMatkul(Integer idMatkul) {
		this.idMatkul = idMatkul;
	}

	@Column(name = "Jam_ngajar", nullable = false, length = 20)
	public String getJamNgajar() {
		return this.jamNgajar;
	}

	public void setJamNgajar(String jamNgajar) {
		this.jamNgajar = jamNgajar;
	}

	@Column(name = "Nama_dosen", nullable = false, length = 50)
	public String getNamaDosen() {
		return this.namaDosen;
	}

	public void setNamaDosen(String namaDosen) {
		this.namaDosen = namaDosen;
	}

	@Column(name = "Mata_kuliah", nullable = false, length = 40)
	public String getMataKuliah() {
		return this.mataKuliah;
	}

	public void setMataKuliah(String mataKuliah) {
		this.mataKuliah = mataKuliah;
	}

	@Column(name = "ruangan_ngajar", nullable = false, length = 10)
	public String getRuanganNgajar() {
		return this.ruanganNgajar;
	}

	public void setRuanganNgajar(String ruanganNgajar) {
		this.ruanganNgajar = ruanganNgajar;
	}

	@Column(name = "HARI", nullable = false, length = 20)
	public String getHari() {
		return this.hari;
	}

	public void setHari(String hari) {
		this.hari = hari;
	}

}
