package com.uhamka.app.model;
// Generated Sep 15, 2019 7:31:18 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Matkul generated by hbm2java
 */
@Entity
@Table(name = "matkul", catalog = "sistem_informasi")
public class Matkul implements java.io.Serializable {

	private String idMatkul;
	private String namaMatkul;
	private Set<Nilai> nilais = new HashSet<Nilai>(0);

	public Matkul() {
	}

	public Matkul(String idMatkul, String namaMatkul) {
		this.idMatkul = idMatkul;
		this.namaMatkul = namaMatkul;
	}

	public Matkul(String idMatkul, String namaMatkul, Set<Nilai> nilais) {
		this.idMatkul = idMatkul;
		this.namaMatkul = namaMatkul;
		this.nilais = nilais;
	}

	@Id

	@Column(name = "ID_MATKUL", unique = true, nullable = false, length = 15)
	public String getIdMatkul() {
		return this.idMatkul;
	}

	public void setIdMatkul(String idMatkul) {
		this.idMatkul = idMatkul;
	}

	@Column(name = "NAMA_MATKUL", nullable = false, length = 30)
	public String getNamaMatkul() {
		return this.namaMatkul;
	}

	public void setNamaMatkul(String namaMatkul) {
		this.namaMatkul = namaMatkul;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "matkul")
	public Set<Nilai> getNilais() {
		return this.nilais;
	}

	public void setNilais(Set<Nilai> nilais) {
		this.nilais = nilais;
	}

}
