package com.uhamka.app.model;
// Generated Sep 15, 2019 7:31:18 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NilaiId generated by hbm2java
 */
@Embeddable
public class NilaiId implements java.io.Serializable {

	private int nim;
	private String idMatkul;

	public NilaiId() {
	}

	public NilaiId(int nim, String idMatkul) {
		this.nim = nim;
		this.idMatkul = idMatkul;
	}

	@Column(name = "Nim", nullable = false)
	public int getNim() {
		return this.nim;
	}

	public void setNim(int nim) {
		this.nim = nim;
	}

	@Column(name = "ID_MATKUL", nullable = false, length = 15)
	public String getIdMatkul() {
		return this.idMatkul;
	}

	public void setIdMatkul(String idMatkul) {
		this.idMatkul = idMatkul;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NilaiId))
			return false;
		NilaiId castOther = (NilaiId) other;

		return (this.getNim() == castOther.getNim())
				&& ((this.getIdMatkul() == castOther.getIdMatkul()) || (this.getIdMatkul() != null
						&& castOther.getIdMatkul() != null && this.getIdMatkul().equals(castOther.getIdMatkul())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNim();
		result = 37 * result + (getIdMatkul() == null ? 0 : this.getIdMatkul().hashCode());
		return result;
	}

}
