package com.uhamka.app.model;
// Generated Sep 15, 2019 7:31:18 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "sistem_informasi")
public class User implements java.io.Serializable {

	private int idUser;
	private String username;
	private String password;
	private String email;
	private String tlp;
	private String type;

	public User() {
	}

	public User(int idUser, String username, String password, String email, String tlp, String type) {
		this.idUser = idUser;
		this.username = username;
		this.password = password;
		this.email = email;
		this.tlp = tlp;
		this.type = type;
	}

	@Id

	@Column(name = "id_user", unique = true, nullable = false)
	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	@Column(name = "username", nullable = false, length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "email", nullable = false, length = 150)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "tlp", nullable = false, length = 20)
	public String getTlp() {
		return this.tlp;
	}

	public void setTlp(String tlp) {
		this.tlp = tlp;
	}

	@Column(name = "type", nullable = false, length = 9)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
